# Name of your workflow
name: Build and Deploy GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Sets the permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks out your repository so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Download the standalone Tailwind binary
      - name: Setup Tailwind CSS
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.3/tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwind
          chmod +x ./tailwind
      
      # 3. NEW DEBUG STEP: Inspect the file system
      - name: Debug File Structure
        run: |
          echo "--- Current Directory ---"
          pwd
          echo "--- File Listing ---"
          ls -laR
          echo "--- tailwind.config.js content ---"
          cat tailwind.config.js
          echo "--- input.css content ---"
          cat input.css

      # 4. Run the build command
      - name: Build Tailwind CSS
        run: ./tailwind --content './index.html,./main.js' -i ./input.css -o ./style.css --minify

      # 5. Configures the GitHub Pages deployment
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      # 6. Gathers the files to be deployed
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      # 7. Deploys the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4